on:
  push:
  workflow_dispatch:

# Run on available environments on GHA
# as on 2020-08-30

name: CITATION-cff full matrix
jobs:
  Validate-CITATION-cff:

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}


    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2 
          
      - name: Validate CITATION.cff
        uses: dieghernan/testaction@main
        with:
          cache-version: 5634
