on:
  push:
  workflow_dispatch:

# Run on available environments on GHA
# as on 2020-08-30

name: CITATION-cff full matrix
jobs:
  Validate-CITATION-cff:

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest}
          - {os: macos-latest}
          - {os: windows-latest}


    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install V8
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y libv8-dev  
          
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - name: Restore R package cache
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-4-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-4-

      - name: Install packages
        run: |
        
          options(repos = c(
             RSPM = 'https://packagemanager.rstudio.com/all',
             CRAN = 'https://cloud.r-project.org'))
        
          Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
          if (isFALSE(requireNamespace("pkgdepends", quietly = TRUE))) {
                    install.packages("pkgdepends")
          }
          
          if (isFALSE(requireNamespace("pak", quietly = TRUE))) {
                    install.packages("pak")
          }
          
          
          pak::pkg_install(c("V8","jsonvalidate" ,"cffr","jsonlite", "sessioninfo"), upgrade = TRUE)
          
          
          if (requireNamespace("sessioninfo", quietly = TRUE)) {
            if (packageVersion("sessioninfo") >= "1.2.1") {
              sessioninfo::session_info(pkgs = "installed", include_base = TRUE)
            } else {
              options(width = 200)
              sessioninfo::session_info(rownames(installed.packages()), include_base=TRUE)
            }
          } else {
            sessionInfo()
          }
          
        shell: Rscript {0}